spring.application.name=clinic
# 1. Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234

# 2. Cấu hình JPA / Hibernate
# Update: Tự động tạo hoặc cập nhật bảng trong DB dựa trên code Java
spring.jpa.hibernate.ddl-auto=update

# In các câu lệnh SQL ra terminal để dễ debug (rất cần khi làm đồ án)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Khai báo Dialect chuẩn cho Postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Chạy server ở cổng 8080 (mặc định)
server.port=8080